server:
  port: 9002

spring:
  webflux:
    base-path: "/api/user-service"
  application:
    name: user-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:cp_mongo_user}
      password: ${MONGODB_PASSWORD:hoyiAMud5UaZr2y}
      database: ${MONGODB_DB_NAME:cp_db}
      authentication-database: ${MONGODB_AUTH_DB_NAME:admin}
      autoIndexCreation: true

logging:
  level:
    root: ERROR
    org.course_planner: INFO