server:
  port: 9002

spring:
  webflux:
    base-path: "/api/user-service"
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: cp_user
      password: rr9TXoAX6gqbEd8E
      database: cp_user_db
      authentication-database: admin
      autoIndexCreation: true

logging:
  level:
    root: ERROR
    org.course_planner: INFO